#!/bin/sh
#author: hhr
#date 2013-10-25

echo "auto install apache for redhat/centos---------->"

# Require root to run this script.
[[ "$(whoami)" != "root" ]] && echo "Please run this script as root." >&2 && exit 1

#set env
log_file="/tmp/$0.log"
auto_install_ip="192.168.1.4"	#default soft download server
save_path="/application/tools"
installDir="/application"

#clear log
>${log_file}
Down_Soft() { 
mkdir -p ${save_path}
cd ${save_path}
if [ ! -f "${soft_package}" ];then
        wget http://172.16.1.237:8000/software/${soft_package} >>${log_file} 2>>${log_file}
        if [ $? -ne 0 ]||[ ! -f "${soft_package}" ];then
                echo "${soft_package} soft is not exist!" |tee -a ${log_file} 
                exit 1
        fi
fi
}
Install_APACHE() { 
soft_package="apachesoft.tar.gz"
soft_short_package="apachesoft"
softname="httpd-2.2.15.tar.gz"
sort_short_name="httpd-2.2.15"
use_short_name="apache"
installDir="/application"
installSoftName="apache2.2.15"
echo "[$(date +%Y%m%d\ %T)]----------start APACHE--------------------------------------->" |tee -a ${log_file}
Down_Soft
#requires rpm package
yum -y install gcc zlib-devel >>${log_file} 2>>${log_file}
echo "install ${softname} ...." |tee -a ${log_file}
cd ${save_path}
tar zxvf ${soft_package}  >>${log_file} 2>>${log_file}
cd ${soft_short_package}
tar zxvf ${softname}  >>${log_file} 2>>${log_file}
cd ${sort_short_name}
./configure --prefix=${installDir}/${installSoftName} \
--enable-deflate \
--enable-headers \
--enable-modules=so \
--enable-so \
--enable-rewrite \
--enable-cgi \
--enable-cache \
--enable-file-cache \
--enable-disk-cache \
--enable-mem-cache  >>${log_file} 2>>${log_file}
make  >>${log_file} 2>>${log_file} && make install  >>${log_file} 2>>${log_file}
[ $? -ne 0 ] && echo 'apache install is fail!' && exit 1
echo 'apache install is ok!'
cd ../
useradd www -M -s /sbin/nologin
ln -s ${installDir}/${installSoftName} ${installDir}/${use_short_name}
echo "${installDir}/${installSoftName}/bin/apachectl start &" >>/etc/rc.d/rc.local
/bin/cp ${installDir}/${use_short_name}/conf/{httpd.conf,httpd.conf-ori}
/bin/cp ${installDir}/${use_short_name}/conf/extra/{httpd-vhosts.conf,httpd-vhosts.conf-ori}
/bin/cp ${installDir}/${use_short_name}/conf/extra/{httpd-mpm.conf,httpd-mpm.conf-ori}
/bin/cp ${installDir}/${use_short_name}/conf/extra/{httpd-default.conf,httpd-default.conf-ori}
/bin/cp httpd.conf-model ${installDir}/${use_short_name}/conf/
/bin/cp httpd-vhosts.conf-model ${installDir}/${use_short_name}/conf/extra/
/bin/cp httpd-mpm.conf-model ${installDir}/${use_short_name}/conf/extra/
/bin/cp httpd-default.conf-model ${installDir}/${use_short_name}/conf/extra/
echo "/application/apache/bin/apachectl -t"
/application/apache/bin/apachectl -t
[ $? -ne 0 ] && echo "apache install is fail!" |tee -a ${log_file} &&exit 1
echo "apache install is ok!" |tee -a ${log_file}
echo "cronolog install ..." |tee -a ${log_file}
tar -zxvf cronolog-1.6.2.tar.gz  >>${log_file} 2>>${log_file}
cd cronolog-1.6.2
./configure >>${log_file} 2>>${log_file} && make >>${log_file} 2>>${log_file} &&make install >>${log_file} 2>>${log_file}
cd ../
echo "install cronolog ok!"
echo "[$(date +%Y%m%d\ %T)]----------end APACHE--------------------------------------->" |tee -a ${log_file}
}
#exec func
Install_APACHE
